# site settings
title: RCKSTR
subtitle: Melómano, Full-Stack Developer, certified SCRUM master
email: rckstr@outlook.com
description: Escribo sobre desarrollo, música, tecnología, teorías de conspiración (not).
baseurl: "" # the subpath of your site, e.g. /blog
url: https://rckstr1.github.io # the base hostname & protocol for your site
author: Adrian Gonzalez

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 2

# social settings
facebook_url: https://www.facebook.com/alexgonzaleztj
github_url: https://github.com/RCKSTR1
linkedin_url: https://www.linkedin.com/in/adriangonzalezb
twitter_url: https://twitter.com/agonzalezTJ

# build settings
markdown: kramdown

sass:
  style: compressed
