# site settings
title: RCKSTR1 en GitHub
subtitle: Melómano, Full-Stack Developer, certified SCRUM master.
email: rckstr@outlook.com
description: Blog sobre desarrollo de software, mejores prácticas, frameworks, lenguajes, y otros temas relacionados en español.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://rckstr1.github.io # the base hostname & protocol for your site
author: Adrian Gonzalez

# dynamic lists
home-posts-preview-count: 2
miniposts-count: 4
postlist-count: 4

# social settings
socialMediaProfiles: [
  { label: Facebook, url: https://www.facebook.com/rckstrblog, icon: fa-facebook },
  { label: GitHub, url: https://github.com/RCKSTR1, icon: fa-github },
  { label: LinkedIn, url: https://www.linkedin.com/in/adriangonzalezb, icon: fa-linkedin },
  { label: Twitter, url: https://twitter.com/agonzalezTJ, icon: fa-twitter },
  { label: Spotify, url: 'https://open.spotify.com/user/dangobah?si=WwZ1FOusRJ-pDbcpV38P-g', icon: fa-spotify },
  { label: Stack Overflow, url: https://stackoverflow.com/users/2088213/rckstr, icon: fa-stack-overflow },
  { label: Email, url: "mailto:rckstr@outlook.com", icon: fa-envelope },
]

# build settings
markdown: kramdown

sass:
  style: compressed
